name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure and make
        run: |
          ./configure
          make -j4

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv lib/.libs/libportaudio.a libportaudio-macos11.a
          mv LICENSE.txt LICENSE

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos11
          path: |
            include.zip
            libportaudio-macos11.a
            LICENSE

  build-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure and make
        run: |
          ./configure
          make -j8

      - name: Prepare output
        run: mv lib/.libs/libportaudio.a libportaudio-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos-arm64
          path: libportaudio-macos-arm64.a

  create-release:
    runs-on: ubuntu-20.04
    needs: [build-macos, build-macos-arm64]
    steps:
      - name: Get build output macos11
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos11

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            include.zip
            libportaudio-macos11.a
            libportaudio-macos-arm64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
